name: Build and push Docker image

# on:
#   schedule:
#     - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - cicd-test


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: cd to ubuntu-latest
      run: pwd && ls && cd DinD-ubuntu-latest/ && pwd && ls

    - name: Build and tag ubuntu-latest Docker image
      run: docker build -t siddiquesa/dind-ubuntu-latest:latest .

    # - name: Push Docker image to Docker Hub
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: .
    #       push: true
    #       tags: your-dockerhub-username/image-name:latest
    #     env:
    #       DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    #       DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

