name: Build and push Docker image

# on:
#   schedule:
#     - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - cicd-test


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and tag ubuntu-latest Docker image
      run: docker build -t siddiquesa/dind-ubuntu-latest:latest /home/runner/work/DinD_Projects/DinD_Projects/DinD-ubuntu-latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: /home/runner/work/DinD_Projects/DinD_Projects/DinD-ubuntu-latest
        push: true
        tags: |
          siddiquesa/dind-ubuntu-latest:latest
          siddiquesa/dind-ubuntu-latest:${{ github.run_number }}