name: Build and push Docker image

# on:
#   schedule:
#     - cron: '0 0 1 * *' # Run every 1st midnight of evry month.

on:
  push:
    branches:
      - cicd-test
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and tag ubuntu-latest Docker image
      run: docker build -t siddiquesa/dind-ubuntu-latest:latest /home/runner/work/DinD_Projects/DinD_Projects/DinD-ubuntu-latest

    - name: Build and tag debian-latest Docker image
      run: docker build -t siddiquesa/dind-debian-latest:latest /home/runner/work/DinD_Projects/DinD_Projects/DinD-debian-latest
    
    - name: Build and tag go-latest Docker image
      run: docker build -t siddiquesa/dind-go-latest:latest /home/runner/work/DinD_Projects/DinD_Projects/DinD-go-latest

    - name: Build and tag k8s-latest Docker image
      run: docker build -t siddiquesa/dind-k8s-latest:latest /home/runner/work/DinD_Projects/DinD_Projects/DinD-k8s-latest

    - name: Build and tag aws-latest Docker image
      run: docker build -t siddiquesa/dind-aws-latest:latest /home/runner/work/DinD_Projects/DinD_Projects/DinD-aws-latest

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Ubuntu Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: /home/runner/work/DinD_Projects/DinD_Projects/DinD-ubuntu-latest
        push: true
        tags: |
          siddiquesa/dind-ubuntu-latest:latest
          siddiquesa/dind-ubuntu-latest:${{ github.run_number }}
    
    - name: Push Debian Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: /home/runner/work/DinD_Projects/DinD_Projects/DinD-debian-latest
        push: true
        tags: |
          siddiquesa/dind-debian-latest:latest
          siddiquesa/dind-debian-latest:${{ github.run_number }}

    - name: Push Go Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: /home/runner/work/DinD_Projects/DinD_Projects/DinD-go-latest
        push: true
        tags: |
          siddiquesa/dind-go-latest:latest
          siddiquesa/dind-go-latest:${{ github.run_number }}

    - name: Push K8s Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: /home/runner/work/DinD_Projects/DinD_Projects/DinD-k8s-latest
        push: true
        tags: |
          siddiquesa/dind-k8s-latest:latest
          siddiquesa/dind-k8s-latest:${{ github.run_number }}

    - name: Push AWS Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: /home/runner/work/DinD_Projects/DinD_Projects/DinD-aws-latest
        push: true
        tags: |
          siddiquesa/dind-aws-latest:latest
          siddiquesa/dind-aws-latest:${{ github.run_number }}
